export const HOME = 'Home';
export const TRENDYOLGO = 'TrendyolGo';
export const FAVOURITES = 'Favourites';
export const CART = 'My Cart';
export const PROFILE = 'Profile';
export const TAB = 'Tab';
export const PRODUCTDETAIL = 'Product Detail';
export const PRODUCTLIST = 'Product List';
export const LOGIN = 'Login';
